language: python
python:
  - '3.6'

notifications:
  email:
    recipients:
    - ox0spy@gmail.com
    on_success: change
    on_failure: always

before_install:
  - export TZ=Asia/Shanghai

install:
  - sudo apt-get install hugo
  - pip install pygments

script:
  - hugo --theme even

deploy:
  provider: pages
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  skip-cleanup: true
  keep-history: true
  on:
    branch: master
